name: Deploy to FTP

on:
  push:
    branches:
      - dev
      - qa
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

    - name: Determine server directory
      id: server-dir
      run: echo "##[set-output name=DIR;]$(if [[ ${{ github.ref }} == 'refs/heads/devnew' ]]; then echo '/devnew.topofmyndcards.com/'; elif [[ ${{ github.ref }} == 'refs/heads/qa' ]]; then echo '/qa.topofmyndcards.com/'; elif [[ ${{ github.ref }} == 'refs/heads/productionnew' ]]; then echo '/public_html_live/'; fi)"

    - name: Upload to bluehost using FTP 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}	
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: ${{ steps.server-dir.outputs.DIR }}
        debug: true 

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: bash

    - name: Run migrations on server
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no topofmyn@162.241.225.171 "cd /home4/topofmyn${{ steps.server-dir.outputs.DIR }} && php spark migrate --all -v"